pipeline {
    agent any

    environment {
        DOCKER_USER = tanishq012
        IMAGE_NAME = "myapp"
    }

    stages {
        stage('Clone Repo') {
            steps {
                git 'https://github.com/your-repo.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    docker.build("${DOCKER_USER}/${IMAGE_NAME}:latest")
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                script {
                    docker.withRegistry('', 'dockerhub-credentials') {
                        docker.image("${DOCKER_USER}/${IMAGE_NAME}:latest").push()
                    }
                }
            }
        }
    }
}